# Site settings
title: Great Barrier Reef
email: dejonge.scott@gmail.com
description: 

# Server
baseurl: "/"
destination: _site
host: 0.0.0.0
port: 4001
url: http://scottdejonge.github.io
encoding: UTF-8

# Excludes
exclude: ["node_modules", "Gemfile", "Gemfile.lock", "commit-hook.sh", "package.json"]

# Collections
# collections:
#   reefs:
#     output: true
#     permalink: /reefs/:path/

# URLs
permalink: pretty

# Build settings
markdown: kramdown

# Syntax Highlighting
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Repo
repo: https://github.com/scottdejonge/great-barrier-reef