# Site settings
title: Great Barrier Reef
email: dejonge.scott@gmail.com
description: 

# Server
baseurl: ""
destination: _site
host: 0.0.0.0
port: 4001
url: http://greatbarrierreef.io
encoding: UTF-8

# Excludes
exclude: ["node_modules", "Gemfile", "Gemfile.lock", "commit-hook.sh", "package.json"]

# Collections
# collections:
#   reefs:
#     output: true
#     permalink: /reefs/:path/

# URLs
permalink: pretty

# Build settings
markdown: kramdown

# Syntax Highlighting
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Repo
repo: https://github.com/scottdejonge/great-barrier-reef/tree/gh-pages
issues: https://github.com/scottdejonge/great-barrier-reef/issues
releases: https://github.com/scottdejonge/great-barrier-reef/releases

# Custom vars
current_version: v0.0.1
twitter: https://twitter.com/scottdejonge